In [5]:
import numpy as np

In [6]:
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])
a * b

array([ 2, 12, 30, 56])

In [7]:
c = np.diag([1,3,5,7])
#c*c
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  9,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 49]])

In [8]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [9]:
c = np.array([1,2,3,4])
np.array_equal(a,b)
np.array_equal(a,c)

True

In [13]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [14]:
np.logical_and(a,b)

array([ True, False, False, False])

In [15]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [16]:
np.log(a)

C:\Users\john\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [17]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [18]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [19]:
# BASIC REDUCTIONS
x = np.array([1,2,3,4])
np.sum(x)

10

In [20]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [21]:
x.sum(axis = 0) #column wise sum

array([3, 3])

In [22]:
x.sum(axis = 1) #row wise sum (second dimension)

array([2, 4])

In [23]:
x = np.array([25,85,105,20])
x.min()

20

In [24]:
x.max()

105

In [25]:
x.argmin() #returns index of minimum element

3

In [26]:
x.argmax() #index of max element **** revisit in optimization

2

In [28]:
a = np.zeros((50,50))
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
np.any(a != 0)

False

In [30]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a <= b) & (b <= c)).all()

True

In [31]:
# STATISTICS


In [33]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [34]:
np.median(x)

1.5

In [35]:
np.median(y,axis=1)

array([2., 5.])

In [36]:
x.std() # full population standard deviation

0.82915619758885

In [38]:
 data = np.loadtxt('populations.txt')

In [39]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [40]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [42]:
populations = data[:, 1:] #return all the row from all columns except 1
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [44]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [47]:
# which species has highest population in each year
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [48]:
# BROADCASTING

In [53]:
a = np.tile(np.arange(0,40,10), (3,1)) #replicate 3 times in row
print(a)
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [54]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [55]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [58]:
a = np.arange(0,40,10)
a.shape

(4,)

In [60]:
a = a[:,np.newaxis] # adds a new axis i.e converts 1d array to 2d array
a.shape

(4, 1)

In [61]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [62]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [64]:
a = np.array([[1,2,3], [4,5,6]])
a.ravel() #Returns a contiguous flattened array

array([1, 2, 3, 4, 5, 6])

In [65]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [68]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [72]:
b = a.ravel()
print(b)
b = b.reshape((3,2))
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [74]:
b[0,0] = 100
b

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [75]:
# note : reshape may also return a copy!!

In [78]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 50
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [79]:
 # ADDING A NEW DIMENSION and DIMENSION SHIFFLING

In [80]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [81]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [82]:
a[0,2,1]

5

In [83]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [84]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [86]:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [87]:
a = np.array([4,3,1,2])
j = np.argsort(a)   # returns position of indices after sorting
j

array([2, 3, 1, 0], dtype=int64)

In [88]:
a[j]

array([1, 2, 3, 4])