In [3]:
import numpy as np
a = np.array([1,2,3,4])
a
a.ndim

1

In [7]:
b = np.array([[0,1,2],[3,4,5]])
b
b.ndim
b.shape

(2, 3)

In [8]:
b = np.arange(1,10,2) # start, end, step
b

array([1, 3, 5, 7, 9])

In [9]:
a = np.linspace(0,1,6) #start, end, number of points (linear space function)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [10]:
# common arrays
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(3)
# return a 2-D array with ones on the diagonal and zero elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3,2)
# 3is no. of rows, 2 is number of columns

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [2]:
#create array with diag function
import numpy as np
a = np.diag([1,3,5,6])
a
#np.diag(a)

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [3]:
#create array using random
#create an array of the given shape and populate with uniform random numbers
a = np.random.rand(4,3)
a

array([[0.68517009, 0.74394453, 0.36937905],
       [0.62190118, 0.78379738, 0.29767362],
       [0.77178384, 0.84803636, 0.30567737],
       [0.87458896, 0.38791423, 0.82332917]])

In [17]:
#create an array with standard normal distribtion
b = np.random.randn(4)
b

array([-0.14480105,  0.27988953,  0.35863226,  1.81070165])

In [18]:
a = np.arange(10,dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
# indexing
a = np.diag([1,2,3,4])
print(a[2,2])
print(a[2,1])
a[2,1] = 5
print(a[2,1]) #assigning value

3
0
5


In [22]:
# slicing
a = np.arange(10)
a[1:8:2] #[start index:end index:step]
a[5:] = 15
a

array([ 0,  1,  2,  3,  4, 15, 15, 15, 15, 15])

In [23]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning (-1 means to process array b in reverse order)
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [24]:
# fancy indexing
a = np.random.randint(0,20,15) # 15 random nos between 0-20
a

array([ 2,  4,  0,  5,  8, 16,  7,  4,  3,  1, 15, 12,  1, 10,  3])

In [25]:
mask = (a%2 == 0)

In [26]:
extract_from_a = a[mask]
extract_from_a

array([ 2,  4,  0,  8, 16,  4, 12, 10])

In [27]:
a[mask] = -1
a

array([-1, -1, -1,  5, -1, -1,  7, -1,  3,  1, 15, -1,  1, -1,  3])

In [28]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
a[[2,3,4,5,3]] # give the list of indexes

array([20, 30, 40, 50, 30])

In [30]:
a[[9,7]] = -222
a

array([   0,   10,   20,   30,   40,   50,   60, -222,   80, -222])